version: "3.9"

services:
  notes-app:
    build:
      context: .          # Current folder containing Dockerfile
      dockerfile: Dockerfile  # Name of your Dockerfile
    container_name: notes-app
    ports:
      - "5500:5050"       # Map host port 5500 → container port 5050
    restart: unless-stopped
