services:
  mongod9b:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwerty

  mongo-exp:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=qwerty
      - ME_CONFIG_MONGODB_SERVER=mongodb
  Notes-app:
    image: node:18-alpine        # Use Node image directly
    container_name: app
    working_dir: /app
    ports:
        - 5050:5050
    environment:
        - NODE_ENV=development
        - MONGO_URL=mongodb://admin:qwerty@mongodb:27017/notesDB
        - DB_NAME=notesDB
        - SESSION_SECRET=supersecret
    command: sh -c "npm install && npm vfstart"
    depends_on:
        - mongodb
