services:
  notes-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: notes-app:latest       # <-- explicitly set image name
    container_name: notes-app
    ports:
      - "5500:5050"
    restart: unless-stopped
